[package]
name = "system76_firmware_update"
version = "1.0.0"
edition = "2018"

[lib]
name = "system76_firmware_update"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
ecflash = { path = "ecflash" }
plain = "0.2.3"
redox_dmi = "0.1.1"
redox_uefi = "0.1.0"
redox_uefi_std = "0.1.0"

[dependencies.orbclient]
git = "https://gitlab.redox-os.org/redox-os/orbclient.git"
branch = "no_std"
features = ["no_std"]

[package.metadata.cargo-xbuild]
memcpy = true
sysroot_path = "build/xbuild"
